search_tweets_api:
  bearer_token: AAAAAAAAAAAAAAAAAAAAALMUKQEAAAAAA4om67zthb7PuApyjA8yKq%2Bf9uE%3De8jhSKRZSokStKijU5DbBuQgKWAzSbxbCqGkma2BcyLaPm5z2A


azure:
  subscription_key: xxxxxxxxxxxxxxxxxxxxxxx